apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-app
    spec:
      serviceAccountName: serviceaccount
      containers:
        - name: {{ .Values.name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-app
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["pods", "deployments", "services", "ingresses"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-app
subjects:
  - kind: ServiceAccount
    name: serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}-app
  apiGroup: rbac.authorization.k8s.io
