apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-app
spec:
  serviceAccountName: serviceaccount
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-app
      annotations:
        ci.build: "{{ .Values.image.tag }}"
    spec:
      containers:
        - name: {{ .Values.name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}

