apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-app
spec:
  type: ClusterIP
  selector:
    app: app1-app
  ports:
    - name: http
      port: {{.Values.port}}
      targetPort: {{.Values.port}}