name: CI-egorik-project

on:
  push:
    branches  : ["dev"]
  pull_request:
    branches  : ["dev"]
 

jobs:
  build:
    runs-on   : ubuntu-latest

    steps:
      - name  : Checkout repository
        uses  : actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build Maven project
        run: mvn -B package -DskipTests

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name and tag
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/app
          TAG=$(git rev-parse --short HEAD)
          echo "IMAGE_NAME=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Output revision
        run: |
          echo "Built image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
