name: java build app

on:
  push:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set unique image tag
        id: set-tag
        run: |
          HASH=$(git hash-object project/src/main/java/com/example/revisionapp/RevisionController.java)
          TAG=$(date +%Y%m%d%H%M%S)-$HASH
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build & push Docker image
        run: |
          docker build --no-cache -t narland/java:${{ steps.set-tag.outputs.tag }} project/
          docker push narland/java:${{ steps.set-tag.outputs.tag }}

  deploy:
    needs: build
    runs-on: arc-runner-set
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Helm
        run: |
          HELM_VERSION="v3.12.3"
          curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/
          rm -rf helm.tar.gz linux-amd64

      - name: Restore kubeconfig
        run: echo "${{ secrets.KUBECONFIG_DATA }}" > $KUBECONFIG

      - name: Deploy App1
        run: |
          helm upgrade --install app1 ./newchart \
            --namespace arc-runners \
            --create-namespace \
            --values ./newchart/values-app1.yaml \
            --set image.repository=narland/java \
            --set image.tag=${{ needs.build.outputs.image-tag }} \
            --set imagePullPolicy=Always \
            --set podAnnotations.ci\\.build=${{ needs.build.outputs.image-tag }}

          kubectl rollout restart deployment app1 -n arc-runners

      - name: Deploy App2
        run: |
          helm upgrade --install app2 ./newchart \
            --namespace arc-runners \
            --create-namespace \
            --values ./newchart/values-app2.yaml \
            --set image.repository=narland/java \
            --set image.tag=${{ needs.build.outputs.image-tag }} \
            --set imagePullPolicy=Always \
            --set podAnnotations.ci\\.build=${{ needs.build.outputs.image-tag }}

          kubectl rollout restart deployment app2 -n arc-runners
