name: build java application

on:
  push:
    branches: ["dev", "main"]

env:
  IMAGE_NAME: narland/java

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
#Тег для того чтобы правильно обновлялось приложение
      - name: set image tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: set up java 
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build Java
        run: mvn -B -f project/pom.xml package -DskipTests

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ steps.vars.outputs.tag }} \
            project/
          docker push $IMAGE_NAME:${{ steps.vars.outputs.tag }}

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig
          chmod 600 kubeconfig

      - name: Deploy App1
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          helm upgrade --install app1 ./newchart \
            -f ./newchart/values-app1.yaml \
            --set image.tag=${{ needs.build.outputs.image_tag }}

      - name: Deploy App2
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          helm upgrade --install app2 ./newchart \
            -f ./newchart/values-app2.yaml \
            --set image.tag=${{ needs.build.outputs.image_tag }}
