name: build java app

on:
  push:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build Java
        run: mvn -B -f project/pom.xml package -DskipTests

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          docker build -t narland/java:$TAG project/
          docker push narland/java:$TAG

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Restore kubeconfig
        run: echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig

      - name: Deploy App1
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          TAG=${{ env.IMAGE_TAG }}
          helm upgrade --install app1 ./newchart \
            --values ./newchart/values-app1.yaml \
            --set image.tag=$TAG

      - name: Deploy App2
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          TAG=${{ env.IMAGE_TAG }}
          helm upgrade --install app2 ./newchart \
            --values ./newchart/values-app2.yaml \
            --set image.tag=$TAG
