name: build java project

on:
  push:
    branches: ["dev", "main"]

jobs:
  build:
    name: CI - Build & Push
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build Java
        run: mvn -B -f project/pom.xml package -DskipTests

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        id: meta
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          docker build -t narland/java:$TAG project/
          docker push narland/java:$TAG

  deploy:
    name: CD - Deploy to Kubernetes
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm (no sudo)
        run: |
          curl -fsSL https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz -o helm.tgz
          tar -xzf helm.tgz
          mkdir -p $HOME/bin
          mv linux-amd64/helm $HOME/bin/helm
          echo "$HOME/bin" >> $GITHUB_PATH
          helm version

      - name: Restore kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig
          chmod 600 kubeconfig

      - name: Deploy app1
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          helm upgrade --install app1 ./newchart \
            --values ./newchart/values-app1.yaml \
            --set image.tag=${{ needs.build.outputs.image_tag }}

      - name: Deploy app2
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          helm upgrade --install app2 ./newchart \
            --values ./newchart/values-app2.yaml \
            --set image.tag=${{ needs.build.outputs.image_tag }}
