name: CICD Pipeline

on:
  push:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build Java application
        run: mvn -B -f project/pom.xml package -DskipTests

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build -t narland/java:latest project/
          docker push narland/java:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm locally
        run: |
          HELM_VERSION="v3.12.3"
          curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz
          mkdir -p $HOME/bin
          mv linux-amd64/helm $HOME/bin/helm
          rm -rf helm.tar.gz linux-amd64
          export PATH=$HOME/bin:$PATH
          helm version

      - name: Restore kubeconfig
        run: echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig

      - name: Deploy App1 Helm
        run: |
          export PATH=$HOME/bin:$PATH
          export KUBECONFIG=$PWD/kubeconfig
          helm upgrade --install app1 ./newchart --values ./newchart/values-app1.yaml

      - name: Deploy App2 Helm
        run: |
          export PATH=$HOME/bin:$PATH
          export KUBECONFIG=$PWD/kubeconfig
          helm upgrade --install app2 ./newchart --values ./newchart/values-app2.yaml
